services:
  - type: web
    name: summarizer-generator
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20
      - key: CHROMA_DB_DIR
        value: /var/tmp/chroma  # ephemeral on Free

    buildCommand: |
      set -e
      cd frontend
      if [ -f package-lock.json ]; then
        npm ci
      else
        npm install
      fi
      npm run build
      cd ..
      rm -rf backend/app/frontend_dist && mkdir -p backend/app/frontend_dist
      cp -r frontend/dist/* backend/app/frontend_dist/
      pip install -r backend/requirements.txt

    startCommand: |
      cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT


