services:
  - type: web
    name: summarizer-generator
    env: python
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 20
      # Optional, your app can read this if needed
      - key: FRONTEND_DIST
        value: ./frontend_dist

      # Add your secrets in the dashboard or here:
      # - key: SEA_LION_API_KEY
      #   sync: false
      # - key: HUGGINGFACE_API_TOKEN
      #   sync: false

    buildCommand: |
      set -e
      cd frontend
      npm ci || npm install
      npm run build
      cd ..
      rm -rf backend/frontend_dist && mkdir -p backend/frontend_dist
      cp -r frontend/dist/* backend/frontend_dist/
      pip install -r backend/requirements.txt

    startCommand: |
      cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
